version: '2'
services:

  # web1:
  #   image: ubuntu
  #   ports:
  #     - 80
  #   links:
  #     - web2
  #   command: tail -f /etc/hosts
  #
  #
  # web3:
  #   image: ubuntu
  #   ports:
  #     - 80
  #   command: tail -f /etc/hosts
  #
  web2:
    image: ubuntu
    ports:
      - 80
    # links:
    #   - web
    command: tail -f /etc/hosts


  nginx:
    # build: ./nginx/
    image: python-app/nginx
    ports:
      - 80:80
    volumes:
      - /usr/src/app/static
    links:
      - web2

  web:
    # build: ./web
    image: python-app/web
    ports:
      - 8000:8000
    volumes:
      - /usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
      SECRET_KEY: 5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_SERVICE: postgres
      DB_PORT: 5432
    # command: tail -f /etc/hosts
    command: /usr/local/bin/gunicorn messanger.wsgi:application -w 2 -b :8000
    links:
      - redis
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - 6379
    volumes:
      - redisdata:/data
